export interface NetworkPort {
  port: number;
  protocol: "TCP" | "UDP" | "TCP/UDP";
  service: string;
  description: string;
}

export const NETWORK_PORTS: NetworkPort[] = [
  { port: 20, protocol: "TCP", service: "FTP", description: "FTP data transfer." },
  { port: 21, protocol: "TCP", service: "FTP", description: "FTP control (commands)." },
  { port: 22, protocol: "TCP", service: "SSH", description: "Secure Shell — remote login and SCP/SFTP file transfer." },
  { port: 23, protocol: "TCP", service: "Telnet", description: "Unencrypted remote terminal access (legacy, insecure)." },
  { port: 25, protocol: "TCP", service: "SMTP", description: "Mail transfer between mail servers." },
  { port: 53, protocol: "TCP/UDP", service: "DNS", description: "Domain Name System queries and zone transfers." },
  { port: 67, protocol: "UDP", service: "DHCP", description: "DHCP server (address assignment)." },
  { port: 68, protocol: "UDP", service: "DHCP", description: "DHCP client." },
  { port: 69, protocol: "UDP", service: "TFTP", description: "Trivial File Transfer Protocol." },
  { port: 80, protocol: "TCP", service: "HTTP", description: "Unencrypted web traffic." },
  { port: 110, protocol: "TCP", service: "POP3", description: "Retrieving email from a mail server." },
  { port: 119, protocol: "TCP", service: "NNTP", description: "Usenet news transfer." },
  { port: 123, protocol: "UDP", service: "NTP", description: "Network Time Protocol — clock synchronization." },
  { port: 135, protocol: "TCP", service: "MS RPC", description: "Windows RPC endpoint mapper." },
  { port: 137, protocol: "UDP", service: "NetBIOS", description: "NetBIOS Name Service." },
  { port: 138, protocol: "UDP", service: "NetBIOS", description: "NetBIOS Datagram Service." },
  { port: 139, protocol: "TCP", service: "NetBIOS", description: "NetBIOS Session Service (legacy SMB over NetBIOS)." },
  { port: 143, protocol: "TCP", service: "IMAP", description: "Retrieving email, with server-side folder management." },
  { port: 161, protocol: "UDP", service: "SNMP", description: "Simple Network Management Protocol — device monitoring." },
  { port: 162, protocol: "UDP", service: "SNMP Trap", description: "Asynchronous SNMP notifications." },
  { port: 179, protocol: "TCP", service: "BGP", description: "Border Gateway Protocol — internet routing." },
  { port: 389, protocol: "TCP", service: "LDAP", description: "Lightweight Directory Access Protocol." },
  { port: 443, protocol: "TCP", service: "HTTPS", description: "Encrypted web traffic (TLS)." },
  { port: 445, protocol: "TCP", service: "SMB", description: "Windows file/printer sharing (Server Message Block)." },
  { port: 465, protocol: "TCP", service: "SMTPS", description: "SMTP over implicit TLS." },
  { port: 514, protocol: "UDP", service: "Syslog", description: "System logging protocol." },
  { port: 515, protocol: "TCP", service: "LPD", description: "Line Printer Daemon protocol." },
  { port: 587, protocol: "TCP", service: "SMTP", description: "Mail submission (client to server, with STARTTLS)." },
  { port: 631, protocol: "TCP/UDP", service: "IPP", description: "Internet Printing Protocol / CUPS." },
  { port: 636, protocol: "TCP", service: "LDAPS", description: "LDAP over implicit TLS." },
  { port: 993, protocol: "TCP", service: "IMAPS", description: "IMAP over implicit TLS." },
  { port: 995, protocol: "TCP", service: "POP3S", description: "POP3 over implicit TLS." },
  { port: 1433, protocol: "TCP", service: "MSSQL", description: "Microsoft SQL Server." },
  { port: 1521, protocol: "TCP", service: "Oracle DB", description: "Oracle database default listener." },
  { port: 1723, protocol: "TCP", service: "PPTP", description: "Point-to-Point Tunneling Protocol (legacy VPN)." },
  { port: 2049, protocol: "TCP/UDP", service: "NFS", description: "Network File System." },
  { port: 2181, protocol: "TCP", service: "ZooKeeper", description: "Apache ZooKeeper client port." },
  { port: 3000, protocol: "TCP", service: "Dev server", description: "Common default for Node.js/React development servers." },
  { port: 3128, protocol: "TCP", service: "Proxy", description: "Common HTTP proxy port (e.g. Squid)." },
  { port: 3268, protocol: "TCP", service: "Global Catalog", description: "Active Directory Global Catalog (LDAP)." },
  { port: 3306, protocol: "TCP", service: "MySQL", description: "MySQL / MariaDB database default port." },
  { port: 3389, protocol: "TCP", service: "RDP", description: "Windows Remote Desktop Protocol." },
  { port: 5000, protocol: "TCP", service: "Dev server", description: "Common default for Flask and other dev servers." },
  { port: 5060, protocol: "TCP/UDP", service: "SIP", description: "Session Initiation Protocol — VoIP signaling." },
  { port: 5432, protocol: "TCP", service: "PostgreSQL", description: "PostgreSQL database default port." },
  { port: 5601, protocol: "TCP", service: "Kibana", description: "Kibana web UI default port." },
  { port: 5672, protocol: "TCP", service: "AMQP", description: "RabbitMQ / AMQP message broker." },
  { port: 5900, protocol: "TCP", service: "VNC", description: "Virtual Network Computing remote desktop." },
  { port: 5984, protocol: "TCP", service: "CouchDB", description: "Apache CouchDB HTTP API." },
  { port: 6379, protocol: "TCP", service: "Redis", description: "Redis in-memory data store default port." },
  { port: 6443, protocol: "TCP", service: "Kubernetes API", description: "Kubernetes API server." },
  { port: 7000, protocol: "TCP", service: "Cassandra", description: "Cassandra inter-node communication." },
  { port: 8000, protocol: "TCP", service: "Dev server", description: "Common alternate HTTP/dev server port." },
  { port: 8080, protocol: "TCP", service: "HTTP alt", description: "Common alternate HTTP port, often used by proxies or Tomcat." },
  { port: 8443, protocol: "TCP", service: "HTTPS alt", description: "Common alternate HTTPS port." },
  { port: 8500, protocol: "TCP", service: "Consul", description: "HashiCorp Consul HTTP API / UI." },
  { port: 9000, protocol: "TCP", service: "PHP-FPM / SonarQube", description: "Common port for PHP-FPM or SonarQube." },
  { port: 9042, protocol: "TCP", service: "Cassandra", description: "Cassandra native client protocol." },
  { port: 9092, protocol: "TCP", service: "Kafka", description: "Apache Kafka broker default port." },
  { port: 9200, protocol: "TCP", service: "Elasticsearch", description: "Elasticsearch HTTP REST API." },
  { port: 9300, protocol: "TCP", service: "Elasticsearch", description: "Elasticsearch inter-node transport." },
  { port: 11211, protocol: "TCP/UDP", service: "Memcached", description: "Memcached default port." },
  { port: 27017, protocol: "TCP", service: "MongoDB", description: "MongoDB database default port." },
];
